// tb_counter_verilator.cpp — Verilator C++ harness for counter.v
//
// Verilator doesn't interpret Verilog testbenches directly; instead it
// transpiles the DUT to C++, and you write a C++ "wrapper" (this file)
// that drives the ports.
//
// Compile and run via the Makefile target `make sim_verilator`.
// Verilator generates a VCD via VerilatedVcdC into waves/counter_verilator.vcd
//
// Key Verilator concepts demonstrated here:
//  • VerilatedContext — replaces the global simulation state
//  • VCD tracing via VerilatedVcdC (must pass --trace flag to verilator)
//  • Manual clock toggling (Verilator has no built-in clock generator)
//  • Checking outputs directly in C++ instead of using $display/$assert

#include "Vcounter.h"          // auto-generated by Verilator from counter.v
#include "verilated.h"
#include "verilated_vcd_c.h"   // VCD tracing support

#include <cstdlib>
#include <iostream>

// Convenience: advance simulation by one full clock cycle (posedge → negedge)
static void tick(VerilatedContext* ctx, Vcounter* dut, VerilatedVcdC* vcd,
                 uint64_t& sim_time) {
    // Posedge
    dut->clk = 1;
    dut->eval();
    if (vcd) vcd->dump(sim_time);
    sim_time += 5;   // 5 ns half-period → 10 ns period = 100 MHz

    // Negedge
    dut->clk = 0;
    dut->eval();
    if (vcd) vcd->dump(sim_time);
    sim_time += 5;
}

int main(int argc, char** argv) {
    VerilatedContext* ctx = new VerilatedContext;
    ctx->commandArgs(argc, argv);

    Vcounter* dut = new Vcounter(ctx, "TOP");

    // Open VCD trace
    Verilated::traceEverOn(true);
    VerilatedVcdC* vcd = new VerilatedVcdC;
    dut->trace(vcd, 99);   // 99 = trace depth (all hierarchy)
    vcd->open("../waves/counter_verilator.vcd");   // relative to m00_toolchain/ → future_prep/waves/

    uint64_t sim_time = 0;
    int errors = 0;

    std::cout << "=== counter smoke test (Verilator) ===" << std::endl;

    // Apply initial values; clk starts low
    dut->clk   = 0;
    dut->rst_n = 0;
    dut->en    = 0;
    dut->eval();
    vcd->dump(sim_time);
    sim_time += 1;

    // T1: Reset holds count at 0
    for (int i = 0; i < 4; i++) tick(ctx, dut, vcd, sim_time);
    if (dut->count != 0) {
        std::cout << "FAIL T1: expected 0 got " << (int)dut->count << std::endl;
        errors++;
    } else {
        std::cout << "PASS T1: reset holds count at 0" << std::endl;
    }

    // T2: Release reset, count stays 0 with en=0
    tick(ctx, dut, vcd, sim_time);
    dut->rst_n = 1;
    for (int i = 0; i < 3; i++) tick(ctx, dut, vcd, sim_time);
    if (dut->count != 0) {
        std::cout << "FAIL T2: count moved without enable, got " << (int)dut->count << std::endl;
        errors++;
    } else {
        std::cout << "PASS T2: count holds when en=0" << std::endl;
    }

    // T3: First increment
    dut->en = 1;
    tick(ctx, dut, vcd, sim_time);
    if (dut->count != 1) {
        std::cout << "FAIL T3: expected 1 got " << (int)dut->count << std::endl;
        errors++;
    } else {
        std::cout << "PASS T3: first increment to 1" << std::endl;
    }

    // T4: Count to 0xFE (253 more ticks)
    for (int i = 0; i < 253; i++) tick(ctx, dut, vcd, sim_time);
    if (dut->count != 0xFE) {
        std::cout << "FAIL T4: expected 0xFE got 0x" << std::hex << (int)dut->count << std::endl;
        errors++;
    } else {
        std::cout << "PASS T4: count at 0xFE before wrap" << std::endl;
    }

    // T5a: wrap signal at 0xFF
    tick(ctx, dut, vcd, sim_time);   // count → 0xFF
    if (!dut->wrap) {
        std::cout << "FAIL T5a: wrap should be 1 at 0xFF, got " << (int)dut->wrap << std::endl;
        errors++;
    } else {
        std::cout << "PASS T5a: wrap=1 when count=0xFF" << std::endl;
    }

    // T5b: rollover to 0
    tick(ctx, dut, vcd, sim_time);   // count → 0x00
    if (dut->count != 0) {
        std::cout << "FAIL T5b: expected rollover to 0 got " << (int)dut->count << std::endl;
        errors++;
    } else {
        std::cout << "PASS T5b: count rolled over to 0" << std::endl;
    }

    // T5c: wrap back to 0 after rollover
    if (dut->wrap) {
        std::cout << "FAIL T5c: wrap should be 0 after rollover" << std::endl;
        errors++;
    } else {
        std::cout << "PASS T5c: wrap=0 after rollover" << std::endl;
    }

    // T6: Freeze with en=0
    dut->en = 0;
    for (int i = 0; i < 5; i++) tick(ctx, dut, vcd, sim_time);
    if (dut->count != 0) {
        std::cout << "FAIL T6: count moved while en=0, got " << (int)dut->count << std::endl;
        errors++;
    } else {
        std::cout << "PASS T6: en=0 freezes count at 0" << std::endl;
    }

    std::cout << "---" << std::endl;
    if (errors == 0)
        std::cout << "ALL TESTS PASSED" << std::endl;
    else
        std::cout << "FAILED: " << errors << " error(s)" << std::endl;
    std::cout << "---" << std::endl;

    vcd->close();
    dut->final();
    delete vcd;
    delete dut;
    delete ctx;

    return (errors == 0) ? 0 : 1;
}
